In [9]:
import numpy as np


In [2]:
a = np.array([1, 2, 3])
a


array([1, 2, 3])

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))


a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [6]:
matrix[0, 0]


1

In [7]:
matrix[1:, :2]


array([[4, 5],
       [7, 8]])

In [8]:
should_include_elements = [True, False, True]
a[should_include_elements]



array([1, 3])

In [9]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')


An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [10]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)


[2, 3, 4, 5, 6]


In [11]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)


[2, 3, 4, 5, 6]


In [12]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))


my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


In [13]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))


my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [14]:
my_array[my_array > 0]


array([ 3, 16])

In [15]:
my_array[my_array % 2 == 0]


array([ 0, 16])

In [16]:
result = my_array % 2
result == 0


array([False,  True, False,  True])

In [17]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]

step_3


array([ 0, 16])

In [18]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')


1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


In [19]:
np.random.randn(10)


array([-0.93592184,  0.42038216, -1.37657169, -0.03908779,  0.34378871,
        0.14965247, -0.41140668, -0.63110875,  0.55746908, -0.06277888])

In [20]:
np.random.randn(3, 4)


array([[ 0.30279015,  0.70455415,  1.75526565,  0.30701092],
       [-1.16291791,  0.54362522, -1.32636393, -0.82116711],
       [-0.9131157 , -1.35984237,  1.91964683, -0.82819641]])

In [21]:
mu = 100
sigma = 30

sigma * np.random.randn(20) + mu


array([ 75.44900868,  97.38869452, 111.13094844, 153.70801275,
       132.2293861 ,  74.69386476, 137.13259949,  75.84709132,
       151.51983828, 129.6561131 , 136.2849052 ,  87.96240384,
       101.49840279, 132.02927457, 173.22911701, 100.71393916,
       171.70377704, 140.47565789,  84.76859213, 131.47510846])

In [22]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
print('np.ones(3)     == {}'.format(np.ones(3)))
print('np.full(3, 17) == {}'.format(np.full(3, 17)))


np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


In [23]:
np.zeros((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.arange(4)


array([0, 1, 2, 3])

In [25]:
np.arange(3, 5, 0.5)


array([3. , 3.5, 4. , 4.5])

In [26]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7)))


min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 


In [28]:
a = np.array([1, 2, 3, 4, 5])


In [29]:

a.std()


1.4142135623730951

In [30]:

a.sum()

15

In [31]:

a.mean()

3.0

In [32]:

a.max()

5

In [33]:
a.min()

1

In [34]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [35]:
# How many negative numbers are there?
a[a < 0]

array([-2, -1, -6, -7])

In [36]:
# How many positive numbers are there?
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [37]:
#How many even positive numbers are there?
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [38]:
# How many even positive numbers are there?
b= a[a > 0]
b[b% 2 == 0]

array([ 4, 10, 12])

In [40]:
# If you were to add 3 to each data point, how many positive numbers would there be?
a+3
a[a>0]

array([ 4, 10, 12, 23,  3])

In [41]:
# If you squared each number, what would the new mean and standard deviation be?

a **2
a.std()

8.06225774829855

In [42]:
a.mean()

3.0

In [43]:
# A common statistical operation on a dataset is centering.
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

b=a-a.mean()
b

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [44]:
# Calculate the z-score for each data point. Recall that the z-score is given by:

b=(a-a.mean())/a.std()
b

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [36]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
print(sum_of_a)

55


In [3]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
print(min_of_a)

1


In [4]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
print(max_of_a)

10


In [20]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
print(mean_of_a)

5.5


In [49]:
# # Exercise 5 - Make a variable named product_of_a to hold the product of 
# multiplying all the numbers in the above list together
np.multiply(a)

TypeError: multiply() takes from 2 to 3 positional arguments but 1 were given

In [42]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
square_of_a= a ** 2
print(square_of_a)

[  1   4   9  16  25  36  49  64  81 100]


In [48]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a= a[a % 2 == 1]
print(odds_in_a)

[1 3 5 7 9]


In [50]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a= a[a % 2 == 0]
print(evens_in_a)

[ 2  4  6  8 10]


In [51]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [66]:
# # Exercise 1 - refactor the following to use numpy.
# Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
    b = np.array(b)
sum_of_b = np.sum(b)
print(sum_of_b)


33


In [53]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [54]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [55]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [56]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
    

In [57]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [58]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [59]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [67]:
# Exercise 9 - print out the shape of the array b.
b.shape


(2, 3)

In [69]:
# Exercise 10 - transpose the array b.
b_2 = b.transpose()
b_2

array([[3, 6],
       [4, 7],
       [5, 8]])

In [70]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
list_b = b.flatten().tolist()
list_b

[3, 4, 5, 6, 7, 8]

In [71]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
#can also use:
b_3 = b.reshape(6,1)
b_3

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [73]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
c = np.array(c)



In [76]:
# Exercise 1 - Find the min, max, sum, and product of c.
print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

1
9
45
362880


In [77]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [79]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [80]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [81]:
# Exercise 5 - Transpose c and print out transposed result.
c2 = c.transpose()
c2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
# Exercise 6 - Get the dot product of the array c with c. 
cprod = c*c
cprod

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [83]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. 
#Answer should be 261
trans= (c*c.transpose()).sum()
trans

261

In [84]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
#Answer should be 131681894400.
trans2 = (c*c.transpose()).prod()
trans2

131681894400

In [65]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2